# Generated by Django 4.2.10 on 2024-02-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('day_work', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('workduration', models.DurationField()),
                ('works_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_works', to='main_app.habits_category')),
            ],
        ),
    ]
