# Generated by Django 4.2.10 on 2024-02-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_daily_works'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daily_Works',
        ),
        migrations.DeleteModel(
            name='Habits_category',
        ),
    ]
