# Generated by Django 4.2.10 on 2024-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spend_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.CharField(max_length=150)),
                ('how_much', models.CharField(max_length=150)),
                ('which_day', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
