# Generated by Django 4.2.10 on 2024-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_spend_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_works',
            name='works_category',
            field=models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad'), ('DAILY', 'Daily')], max_length=150),
        ),
        migrations.DeleteModel(
            name='Habits_category',
        ),
    ]
